### ISSUE TITLE
Call to authenticate fails from .NET

### ISSUE THREAD

**Issue by dickerstu** [M-Files/Libraries.MFWSClient#28]
The call to /REST/server/authenticationtokens in MFWSClient.cs has suddenly stopped working. The error we receive is 

System.Net.WebException: The SSL connection could not be established, see inner exception.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   
 This began happening on 12/21/2023. Anyone else having this issue?

**Comment by dickerstu** [comment]
We added this temporary fix in our global.asax file. M-Files must have changed something something in their load balancer or IIS configuration that has caused the negotiate step of TLS to fail. It only is failing on Windows 11/Server 2020. Our Linux containers seem to work. 

// force TLS 1.2 because of M-Files. This is a "temporary" fix
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

**Comment by CraigHawker** [comment]
TLS 1.2 has been a requirement in the M-Files cloud for some time. Where is your vault located? What changed on your server on 21st December; was it an M-Files install?

That said, the core issue is because the default protocols supported by dotnet are defined by dotnet and/or the OS that the code is running on. We could alter the library to perhaps attempt to include 1.2 into the supported protocols, but we'd then have to possibly do the same with other versions in the future... I'm not sure I like that.

**Comment by dickerstu** [comment]
If your vault is hosted in M-Files cloud, it uses Azure app services. So this is interesting https://techcommunity.microsoft.com/t5/apps-on-azure-blog/upcoming-tls-1-3-on-azure-app-service-for-web-apps-functions-and/ba-p/3974138
