### ISSUE TITLE
Request: also get the build-in properties

### ISSUE THREAD

**Issue by AndyVanDePutte** [M-Files/Libraries.MFWSClient#4]
Hi,

I was wondring if it's possible to also get the build-in properties when calling the method

.ObjectPropertyOperations.GetProperties(ObjVer)

Some properties (I have the Idea that this are the build-in properties) are not included in these results.
I also have the feeling that the autonumber-properties are not included.

Is it possible that OR
a) these methods are extended to also inlcude these build-in properties
OR
b) we can ask a specific SINGLE parameter through a GetProperty(ObjVer, PropDef) method?

Best regards,
Andy

**Comment by CraigHawker** [comment]
Hi Andy,

1. The [GetProperties](https://github.com/M-Files/Libraries.MFWSClient/blob/master/MFaaP.MFWSClient/MFWSVaultObjectPropertyOperations.cs#L200) call hits [this endpoint](https://developer.m-files.com/APIs/REST-API/Reference/resources/objects/type/objectid/version/properties/).  Which properties seem to be missing from the returned data?

2. It would be quite simple to add a GetProperty method that hits [this endpoint](https://developer.m-files.com/APIs/REST-API/Reference/resources/objects/type/objectid/version/properties/id/), but at first glance it appears that the module doesn't yet have that method added; I guess simply because for most integrations they require more than one property, so retrieval of individual properties is not especially efficient.

Regards,

Craig.

**Comment by AndyVanDePutte** [comment]
Hi Craig,

First, I was missing the properties 38 and 39 (workflow and state).
I did some further investigation and I noticed that for some Objects, the method ".ObjectPropertyOperations.GetProperties(ObjVer)" gives me not always the same number of properties

Because I was only looking to the first objects, I thought that these fields were not included. But that conclusion was not right.

Now we see that some of them include 38 and 39 as others don't include them... Any idea why this is sometimes different?
All the objects where of the same type 129 and the same class 38.

Second, I was also missing some Auto-Number field/property. But we need to do some further investigations on this.

**Comment by CraigHawker** [comment]
Different objects will contain different properties, depending on a number of factors.  You should check the returned collection to see whether it contains a value for the property definition that you're interested in.  The type and class data you've provided isn't directly useful as they are internal to your implementation.

If you're finding some inconsistency with the data returned around automatic numbers then please do let me know, although I believe that these should be returned in the data you get from this call.
